CREATE TABLE FUT_LEAGUES (
    LG_ID SERIAL PRIMARY KEY,
    LG_NAME VARCHAR(255) NOT NULL,
    LG_COUNTRY VARCHAR(255) NOT NULL,
    LG_TYPE VARCHAR(255) NOT NULL,
    LG_REQUEST VARCHAR(255) NOT NULL
);

CREATE TABLE FUT_TEAMS (
    TM_ID SERIAL PRIMARY KEY,
    TM_NAME VARCHAR(255) UNIQUE NOT NULL,
    TM_COUNTRY VARCHAR(255) NOT NULL,
    TM_LOGO VARCHAR(255) NOT NULL,
    TM_ID_API VARCHAR(255) UNIQUE
);

CREATE TABLE FUT_LEAGUES_TEAMS (
    LG_ID INTEGER,
    TM_ID INTEGER,
    FOREIGN KEY (LG_ID) REFERENCES FUT_LEAGUES(LG_ID),
    FOREIGN KEY (TM_ID) REFERENCES FUT_TEAMS(TM_ID)
);

CREATE TABLE FUT_MATCHES (
    MT_ID SERIAL PRIMARY KEY,
    MT_LEAGUE INTEGER,
    MT_DATE TIMESTAMP,
    MT_VENUE VARCHAR(255),
    MT_HOME INTEGER,
    MT_AWAY INTEGER,
    MT_HOME_SCORE INTEGER,
    MT_AWAY_SCORE INTEGER,
    MT_STATE VARCHAR(255),
    MT_STATUS VARCHAR(255),
    FOREIGN KEY (MT_LEAGUE) REFERENCES FUT_LEAGUES(LG_ID),
    FOREIGN KEY (MT_HOME) REFERENCES FUT_TEAMS(TM_ID),
    FOREIGN KEY (MT_AWAY) REFERENCES FUT_TEAMS(TM_ID)
);

CREATE TABLE FUT_ETL_LOGS (
    ETL_ID SERIAL PRIMARY KEY,
    ETL_DATE TIMESTAMP,
    ETL_TABLE VARCHAR(255),
    ETL_REGISTROS INTEGER,
    ETL_STATUS VARCHAR(255),
    ETL_MESSAGE TEXT
);